// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG5fW6CwlAyeYFmaAcBkMl0wRYmVAGRF0',
    appId: '1:957127238215:android:989025fe77dd963332c762',
    messagingSenderId: '957127238215',
    projectId: 'whatapp-flutter',
    storageBucket: 'whatapp-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4jT3M0Usk96TPoHgQWQ0_8_nc9tP4tkg',
    appId: '1:957127238215:ios:e337efe76671c8b832c762',
    messagingSenderId: '957127238215',
    projectId: 'whatapp-flutter',
    storageBucket: 'whatapp-flutter.appspot.com',
    iosClientId: '957127238215-6h4ab3ajogkdrrb2crf008nta2ueo81p.apps.googleusercontent.com',
    iosBundleId: 'github.dionlaranjeira.whatappClone',
  );
}
